In [46]:
import seaborn as sns
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [37]:
ds=pd.read_csv("product_data.csv")
ds

,CustomerID,Product,Price,Quantity,City,PurchaseDate
0,1052,Desktop,NaN,4.0,Bangalore,2021-06-30
1,1041,Desktop,NaN,3.0,Delhi,2023-01-21
2,1057,Smartphone,forty-five thousand,2.0,Bangalore,2023-04-06
3,1038,Tablet,45000.0,1.0,Chennai,2023-07-05
4,1013,Smartphone,45000.0,NaN,Mumbai,2022-04-11
...,...,...,...,...,...,...
120,1074,Laptop,45000.0,NaN,Bangalore,2021-08-14
121,1017,Desktop,45000.0,NaN,Pune,2022-08-09
122,1075,Desktop,30000.0,1.0,Pune,2021-09-28
123,1008,Laptop,60000.0,1.0,Chennai,2021-09-13
124,1073,Laptop,15000.0,NaN,Delhi,2021-01-01

In [38]:
print(ds.to_string())

     CustomerID     Product                Price Quantity       City PurchaseDate
0          1052     Desktop                  NaN      4.0  Bangalore   2021-06-30
1          1041     Desktop                  NaN      3.0      Delhi   2023-01-21
2          1057  Smartphone  forty-five thousand      2.0  Bangalore   2023-04-06
3          1038      Tablet              45000.0      1.0    Chennai   2023-07-05
4          1013  Smartphone              45000.0      NaN     Mumbai   2022-04-11
5          1094      Laptop              60000.0      two     Mumbai   2022-03-12
6          1004      Laptop              30000.0      2.0    Chennai   2022-02-25
7          1034      Laptop              30000.0      2.0    Chennai   2022-12-22
8          1086      Laptop              30000.0      3.0      Delhi   2022-10-23
9          1092     Desktop              30000.0      3.0     Mumbai   2022-03-12
10         1074      Laptop              45000.0      NaN  Bangalore   2021-08-14
11         1017     Desktop              45000.0      NaN       Pune   2022-08-09
12         1075     Desktop              30000.0      1.0       Pune   2021-09-28
13         1008      Laptop              60000.0      1.0    Chennai   2021-09-13
14         1073      Laptop              15000.0      NaN      Delhi   2021-01-01
15         1057      Tablet              15000.0      NaN       Pune   2022-11-22
16         1016  Smartphone              60000.0      4.0     Mumbai   2023-09-03
17         1006      Laptop              30000.0      3.0    Chennai   2022-07-10
18         1045      Tablet              45000.0      1.0  Bangalore   2023-01-21
19         1012      Tablet              15000.0      3.0    Chennai   2023-07-20
20         1039  Smartphone                  NaN      3.0  Bangalore   2021-02-15
21         1041     Desktop                  NaN      NaN    Chennai   2021-01-01
22         1008      Laptop              60000.0      4.0    Chennai   2021-04-16
23         1049  Smartphone              30000.0      2.0    Chennai   2022-02-25
24         1026      Laptop              15000.0      4.0  Bangalore   2023-03-22
25         1065      Tablet              30000.0      4.0  Bangalore   2021-01-31
26         1004      Tablet              15000.0      3.0    Chennai   2022-04-11
27         1028     Desktop              60000.0      4.0       Pune   2021-05-16
28         1036      Tablet              60000.0      1.0      Delhi   2022-05-11
29         1037      Tablet                  NaN      3.0      Delhi   2023-03-22
30         1082  Smartphone              30000.0      1.0      Delhi   2022-04-11
31         1007      Laptop                  NaN      2.0  Bangalore   2023-01-06
32         1064      Laptop              30000.0      3.0  Bangalore   2021-04-01
33         1085  Smartphone                  NaN      2.0       Pune   2021-04-16
34         1016     Desktop              45000.0      3.0      Delhi   2023-08-19
35         1070      Laptop              45000.0      NaN      Delhi   2023-04-21
36         1088      Tablet              45000.0      4.0    Chennai   2023-09-18
37         1044      Laptop              45000.0      NaN  Bangalore   2023-05-21
38         1003      Tablet              15000.0      2.0      Delhi   2023-12-02
39         1035     Desktop              45000.0      4.0       Pune   2023-03-07
40         1069  Smartphone              60000.0      3.0       Pune   2023-09-18
41         1030      Laptop              60000.0      4.0      Delhi   2023-01-21
42         1018  Smartphone              15000.0      1.0  Bangalore   2021-04-16
43         1060      Laptop              45000.0      4.0       Pune   2022-05-11
44         1053      Tablet              45000.0      1.0    Chennai   2022-05-26
45         1038  Smartphone              45000.0      4.0       Pune   2022-04-11
46         1090      Laptop                  NaN      1.0     Mumbai   2022-11-07
47         1073      Tablet              30000.0      2.0     Mumbai   2021-08-14
48         1089  Smartphone                  NaN      NaN  Bangalore   2023-10-03
49         1018  Smartphone              30000.0      3.0      Delhi   2022-06-25
50         1038      Laptop              45000.0      4.0  Bangalore   2023-03-07
51         1066      Laptop              45000.0      NaN  Bangalore   2021-07-15
52         1044      Laptop                  NaN      3.0  Bangalore   2023-03-22
53         1012      Tablet                  NaN      3.0  Bangalore   2022-12-07
54         1091      Laptop              30000.0      1.0    Chennai   2021-04-01
55         1057  Smartphone              60000.0      2.0    Chennai   2021-04-01
56         1019  Smartphone              30000.0      2.0       Pune   2022-04-26
57         1091      Laptop                  NaN      NaN     Mumbai   2021-11-27
58         1071      Laptop                  NaN      2.0  Bangalore   2021-09-28
59         1060     Desktop              15000.0      4.0       Pune   2021-09-28
60         1038  Smartphone                  NaN      2.0     Mumbai   2022-06-10
61         1000      Tablet              15000.0      NaN      Delhi   2022-02-25
62         1002     Desktop              60000.0      2.0    Chennai   2023-06-05
63         1076      Laptop              30000.0      4.0     Mumbai   2021-01-16
64         1091      Laptop              30000.0      1.0      Delhi   2021-01-01
65         1061  Smartphone              15000.0      NaN     Mumbai   2022-11-22
66         1062      Laptop              30000.0      1.0    Chennai   2023-10-18
67         1024      Tablet                  NaN      1.0    Chennai   2021-10-13
68         1055  Smartphone              45000.0      1.0       Pune   2021-05-31
69         1032      Laptop              15000.0      3.0  Bangalore   2021-01-16
70         1037  Smartphone              30000.0      3.0     Mumbai   2023-09-18
71         1005      Laptop              15000.0      1.0     Mumbai   2021-06-15
72         1057      Laptop              15000.0      NaN      Delhi   2021-10-13
73         1043      Laptop              45000.0      4.0    Chennai   2021-03-02
74         1044      Tablet                  NaN      4.0     Mumbai   2022-06-25
75         1031      Tablet              15000.0      2.0    Chennai   2022-07-10
76         1044  Smartphone              30000.0      NaN     Mumbai   2021-05-01
77         1060      Laptop              60000.0      3.0       Pune   2023-02-20
78         1046      Laptop              15000.0      1.0  Bangalore   2022-10-08
79         1020      Tablet              15000.0      2.0     Mumbai   2021-12-12
80         1079      Laptop              45000.0      4.0    Chennai   2022-03-12
81         1084      Tablet                  NaN      3.0       Pune   2023-05-21
82         1074      Laptop              60000.0      3.0     Mumbai   2021-07-15
83         1035  Smartphone              30000.0      1.0      Delhi   2021-05-01
84         1098      Laptop              60000.0      4.0  Bangalore   2022-08-09
85         1018      Laptop              30000.0      NaN     Mumbai   2023-09-03
86         1019     Desktop                  NaN      3.0       Pune   2021-12-27
87         1056      Tablet              30000.0      1.0      Delhi   2023-12-17
88         1017      Laptop              45000.0      NaN       Pune   2021-11-12
89         1046      Laptop              45000.0      4.0       Pune   2021-02-15
90         1048     Desktop              45000.0      3.0      Delhi   2022-01-11
91         1013     Desktop              45000.0      NaN       Pune   2023-05-06
92         1014      Tablet              60000.0      NaN      Delhi   2022-02-25
93         1030     Desktop                  NaN      NaN     Mumbai   2022-06-25
94         1000  Smartphone              30000.0      3.0      Delhi   2023-11-02
95         1053     Desktop              30000.0      3.0      Delhi   2021-09-13
96         1002  Smartphone              45000.0      2.0  Bangalore   2022-09-08
97         1015      Tablet              45000.0      4.0      Delhi   2022-08-24
98         1086      Tablet              15000.0      1.0      Delhi   2022-07-10
99         1056      Tablet                  NaN      NaN     Mumbai   2022-05-11
100        1074      Tablet              60000.0      2.0  Bangalore   2021-08-29
101        1011      Tablet              30000.0      1.0    Chennai   2022-06-25
102        1073  Smartphone              15000.0      2.0     Mumbai   2021-12-27
103        1095  Smartphone              15000.0      3.0     Mumbai   2022-01-26
104        1015      Tablet              30000.0      NaN    Chennai   2023-04-21
105        1071     Desktop              60000.0      1.0      Delhi   2022-03-27
106        1075      Laptop              15000.0      1.0       Pune   2021-03-17
107        1023      Tablet              15000.0      1.0  Bangalore   2022-08-09
108        1027     Desktop                  NaN      1.0       Pune   2021-06-15
109        1007      Laptop              60000.0      1.0    Chennai   2023-02-20
110        1091      Tablet              15000.0      2.0     Mumbai   2023-11-17
111        1035      Tablet              60000.0      NaN     Mumbai   2021-05-16
112        1089  Smartphone              30000.0      3.0  Bangalore   2022-10-23
113        1007      Laptop              45000.0      3.0     Mumbai   2021-08-29
114        1057      Laptop              15000.0      3.0     Mumbai   2022-01-11
115        1059     Desktop                  NaN      3.0  Bangalore   2023-07-05
116        1049  Smartphone              30000.0      2.0  Bangalore   2022-11-07
117        1027  Smartphone              60000.0      4.0    Chennai   2023-08-04
118        1091  Smartphone              30000.0      NaN     Mumbai   2021-01-16
119        1040  Smartphone              15000.0      1.0     Mumbai   2023-03-07
120        1074      Laptop              45000.0      NaN  Bangalore   2021-08-14
121        1017     Desktop              45000.0      NaN       Pune   2022-08-09
122        1075     Desktop              30000.0      1.0       Pune   2021-09-28
123        1008      Laptop              60000.0      1.0    Chennai   2021-09-13
124        1073      Laptop              15000.0      NaN      Delhi   2021-01-01

In [39]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    125 non-null    int64
 1   Product       125 non-null    object
 2   Price         103 non-null    object
 3   Quantity      98 non-null     object
 4   City          125 non-null    object
 5   PurchaseDate  125 non-null    object
dtypes: int64(1), object(5)
memory usage: 6.0+ KB

In [40]:
ds.loc[2,'Price']=45000
ds.loc[5,'Quantity']=2

In [41]:
ds['Price']=pd.to_numeric(ds['Price'])
ds['Quantity']=pd.to_numeric(ds['Quantity'])

In [42]:
ds['PurchaseDate']=pd.to_datetime(ds['PurchaseDate'])

In [43]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    125 non-null    int64
 1   Product       125 non-null    object
 2   Price         103 non-null    float64
 3   Quantity      98 non-null     float64
 4   City          125 non-null    object
 5   PurchaseDate  125 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 6.0+ KB

In [47]:
x=ds['Price'].mean()
ds['Price'].fillna(x,inplace=True)

In [45]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    125 non-null    int64
 1   Product       125 non-null    object
 2   Price         125 non-null    float64
 3   Quantity      98 non-null     float64
 4   City          125 non-null    object
 5   PurchaseDate  125 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 6.0+ KB

In [48]:
x=ds['Quantity'].median()
ds['Quantity'].fillna(x,inplace=True)

In [49]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    125 non-null    int64
 1   Product       125 non-null    object
 2   Price         125 non-null    float64
 3   Quantity      125 non-null    float64
 4   City          125 non-null    object
 5   PurchaseDate  125 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 6.0+ KB

In [50]:
print(ds.to_string())

     CustomerID     Product         Price  Quantity       City PurchaseDate
0          1052     Desktop  36262.135922       4.0  Bangalore   2021-06-30
1          1041     Desktop  36262.135922       3.0      Delhi   2023-01-21
2          1057  Smartphone  45000.000000       2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.000000       1.0    Chennai   2023-07-05
4          1013  Smartphone  45000.000000       2.5     Mumbai   2022-04-11
5          1094      Laptop  60000.000000       2.0     Mumbai   2022-03-12
6          1004      Laptop  30000.000000       2.0    Chennai   2022-02-25
7          1034      Laptop  30000.000000       2.0    Chennai   2022-12-22
8          1086      Laptop  30000.000000       3.0      Delhi   2022-10-23
9          1092     Desktop  30000.000000       3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.000000       2.5  Bangalore   2021-08-14
11         1017     Desktop  45000.000000       2.5       Pune   2022-08-09
12         1075     Desktop  30000.000000       1.0       Pune   2021-09-28
13         1008      Laptop  60000.000000       1.0    Chennai   2021-09-13
14         1073      Laptop  15000.000000       2.5      Delhi   2021-01-01
15         1057      Tablet  15000.000000       2.5       Pune   2022-11-22
16         1016  Smartphone  60000.000000       4.0     Mumbai   2023-09-03
17         1006      Laptop  30000.000000       3.0    Chennai   2022-07-10
18         1045      Tablet  45000.000000       1.0  Bangalore   2023-01-21
19         1012      Tablet  15000.000000       3.0    Chennai   2023-07-20
20         1039  Smartphone  36262.135922       3.0  Bangalore   2021-02-15
21         1041     Desktop  36262.135922       2.5    Chennai   2021-01-01
22         1008      Laptop  60000.000000       4.0    Chennai   2021-04-16
23         1049  Smartphone  30000.000000       2.0    Chennai   2022-02-25
24         1026      Laptop  15000.000000       4.0  Bangalore   2023-03-22
25         1065      Tablet  30000.000000       4.0  Bangalore   2021-01-31
26         1004      Tablet  15000.000000       3.0    Chennai   2022-04-11
27         1028     Desktop  60000.000000       4.0       Pune   2021-05-16
28         1036      Tablet  60000.000000       1.0      Delhi   2022-05-11
29         1037      Tablet  36262.135922       3.0      Delhi   2023-03-22
30         1082  Smartphone  30000.000000       1.0      Delhi   2022-04-11
31         1007      Laptop  36262.135922       2.0  Bangalore   2023-01-06
32         1064      Laptop  30000.000000       3.0  Bangalore   2021-04-01
33         1085  Smartphone  36262.135922       2.0       Pune   2021-04-16
34         1016     Desktop  45000.000000       3.0      Delhi   2023-08-19
35         1070      Laptop  45000.000000       2.5      Delhi   2023-04-21
36         1088      Tablet  45000.000000       4.0    Chennai   2023-09-18
37         1044      Laptop  45000.000000       2.5  Bangalore   2023-05-21
38         1003      Tablet  15000.000000       2.0      Delhi   2023-12-02
39         1035     Desktop  45000.000000       4.0       Pune   2023-03-07
40         1069  Smartphone  60000.000000       3.0       Pune   2023-09-18
41         1030      Laptop  60000.000000       4.0      Delhi   2023-01-21
42         1018  Smartphone  15000.000000       1.0  Bangalore   2021-04-16
43         1060      Laptop  45000.000000       4.0       Pune   2022-05-11
44         1053      Tablet  45000.000000       1.0    Chennai   2022-05-26
45         1038  Smartphone  45000.000000       4.0       Pune   2022-04-11
46         1090      Laptop  36262.135922       1.0     Mumbai   2022-11-07
47         1073      Tablet  30000.000000       2.0     Mumbai   2021-08-14
48         1089  Smartphone  36262.135922       2.5  Bangalore   2023-10-03
49         1018  Smartphone  30000.000000       3.0      Delhi   2022-06-25
50         1038      Laptop  45000.000000       4.0  Bangalore   2023-03-07
51         1066      Laptop  45000.000000       2.5  Bangalore   2021-07-15
52         1044      Laptop  36262.135922       3.0  Bangalore   2023-03-22
53         1012      Tablet  36262.135922       3.0  Bangalore   2022-12-07
54         1091      Laptop  30000.000000       1.0    Chennai   2021-04-01
55         1057  Smartphone  60000.000000       2.0    Chennai   2021-04-01
56         1019  Smartphone  30000.000000       2.0       Pune   2022-04-26
57         1091      Laptop  36262.135922       2.5     Mumbai   2021-11-27
58         1071      Laptop  36262.135922       2.0  Bangalore   2021-09-28
59         1060     Desktop  15000.000000       4.0       Pune   2021-09-28
60         1038  Smartphone  36262.135922       2.0     Mumbai   2022-06-10
61         1000      Tablet  15000.000000       2.5      Delhi   2022-02-25
62         1002     Desktop  60000.000000       2.0    Chennai   2023-06-05
63         1076      Laptop  30000.000000       4.0     Mumbai   2021-01-16
64         1091      Laptop  30000.000000       1.0      Delhi   2021-01-01
65         1061  Smartphone  15000.000000       2.5     Mumbai   2022-11-22
66         1062      Laptop  30000.000000       1.0    Chennai   2023-10-18
67         1024      Tablet  36262.135922       1.0    Chennai   2021-10-13
68         1055  Smartphone  45000.000000       1.0       Pune   2021-05-31
69         1032      Laptop  15000.000000       3.0  Bangalore   2021-01-16
70         1037  Smartphone  30000.000000       3.0     Mumbai   2023-09-18
71         1005      Laptop  15000.000000       1.0     Mumbai   2021-06-15
72         1057      Laptop  15000.000000       2.5      Delhi   2021-10-13
73         1043      Laptop  45000.000000       4.0    Chennai   2021-03-02
74         1044      Tablet  36262.135922       4.0     Mumbai   2022-06-25
75         1031      Tablet  15000.000000       2.0    Chennai   2022-07-10
76         1044  Smartphone  30000.000000       2.5     Mumbai   2021-05-01
77         1060      Laptop  60000.000000       3.0       Pune   2023-02-20
78         1046      Laptop  15000.000000       1.0  Bangalore   2022-10-08
79         1020      Tablet  15000.000000       2.0     Mumbai   2021-12-12
80         1079      Laptop  45000.000000       4.0    Chennai   2022-03-12
81         1084      Tablet  36262.135922       3.0       Pune   2023-05-21
82         1074      Laptop  60000.000000       3.0     Mumbai   2021-07-15
83         1035  Smartphone  30000.000000       1.0      Delhi   2021-05-01
84         1098      Laptop  60000.000000       4.0  Bangalore   2022-08-09
85         1018      Laptop  30000.000000       2.5     Mumbai   2023-09-03
86         1019     Desktop  36262.135922       3.0       Pune   2021-12-27
87         1056      Tablet  30000.000000       1.0      Delhi   2023-12-17
88         1017      Laptop  45000.000000       2.5       Pune   2021-11-12
89         1046      Laptop  45000.000000       4.0       Pune   2021-02-15
90         1048     Desktop  45000.000000       3.0      Delhi   2022-01-11
91         1013     Desktop  45000.000000       2.5       Pune   2023-05-06
92         1014      Tablet  60000.000000       2.5      Delhi   2022-02-25
93         1030     Desktop  36262.135922       2.5     Mumbai   2022-06-25
94         1000  Smartphone  30000.000000       3.0      Delhi   2023-11-02
95         1053     Desktop  30000.000000       3.0      Delhi   2021-09-13
96         1002  Smartphone  45000.000000       2.0  Bangalore   2022-09-08
97         1015      Tablet  45000.000000       4.0      Delhi   2022-08-24
98         1086      Tablet  15000.000000       1.0      Delhi   2022-07-10
99         1056      Tablet  36262.135922       2.5     Mumbai   2022-05-11
100        1074      Tablet  60000.000000       2.0  Bangalore   2021-08-29
101        1011      Tablet  30000.000000       1.0    Chennai   2022-06-25
102        1073  Smartphone  15000.000000       2.0     Mumbai   2021-12-27
103        1095  Smartphone  15000.000000       3.0     Mumbai   2022-01-26
104        1015      Tablet  30000.000000       2.5    Chennai   2023-04-21
105        1071     Desktop  60000.000000       1.0      Delhi   2022-03-27
106        1075      Laptop  15000.000000       1.0       Pune   2021-03-17
107        1023      Tablet  15000.000000       1.0  Bangalore   2022-08-09
108        1027     Desktop  36262.135922       1.0       Pune   2021-06-15
109        1007      Laptop  60000.000000       1.0    Chennai   2023-02-20
110        1091      Tablet  15000.000000       2.0     Mumbai   2023-11-17
111        1035      Tablet  60000.000000       2.5     Mumbai   2021-05-16
112        1089  Smartphone  30000.000000       3.0  Bangalore   2022-10-23
113        1007      Laptop  45000.000000       3.0     Mumbai   2021-08-29
114        1057      Laptop  15000.000000       3.0     Mumbai   2022-01-11
115        1059     Desktop  36262.135922       3.0  Bangalore   2023-07-05
116        1049  Smartphone  30000.000000       2.0  Bangalore   2022-11-07
117        1027  Smartphone  60000.000000       4.0    Chennai   2023-08-04
118        1091  Smartphone  30000.000000       2.5     Mumbai   2021-01-16
119        1040  Smartphone  15000.000000       1.0     Mumbai   2023-03-07
120        1074      Laptop  45000.000000       2.5  Bangalore   2021-08-14
121        1017     Desktop  45000.000000       2.5       Pune   2022-08-09
122        1075     Desktop  30000.000000       1.0       Pune   2021-09-28
123        1008      Laptop  60000.000000       1.0    Chennai   2021-09-13
124        1073      Laptop  15000.000000       2.5      Delhi   2021-01-01

In [51]:
ds['Price']=ds['Price'].round(2)
ds['Quantity']=ds['Quantity'].round(0)

In [52]:
print(ds.to_string())

     CustomerID     Product     Price  Quantity       City PurchaseDate
0          1052     Desktop  36262.14       4.0  Bangalore   2021-06-30
1          1041     Desktop  36262.14       3.0      Delhi   2023-01-21
2          1057  Smartphone  45000.00       2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.00       1.0    Chennai   2023-07-05
4          1013  Smartphone  45000.00       2.0     Mumbai   2022-04-11
5          1094      Laptop  60000.00       2.0     Mumbai   2022-03-12
6          1004      Laptop  30000.00       2.0    Chennai   2022-02-25
7          1034      Laptop  30000.00       2.0    Chennai   2022-12-22
8          1086      Laptop  30000.00       3.0      Delhi   2022-10-23
9          1092     Desktop  30000.00       3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.00       2.0  Bangalore   2021-08-14
11         1017     Desktop  45000.00       2.0       Pune   2022-08-09
12         1075     Desktop  30000.00       1.0       Pune   2021-09-28
13         1008      Laptop  60000.00       1.0    Chennai   2021-09-13
14         1073      Laptop  15000.00       2.0      Delhi   2021-01-01
15         1057      Tablet  15000.00       2.0       Pune   2022-11-22
16         1016  Smartphone  60000.00       4.0     Mumbai   2023-09-03
17         1006      Laptop  30000.00       3.0    Chennai   2022-07-10
18         1045      Tablet  45000.00       1.0  Bangalore   2023-01-21
19         1012      Tablet  15000.00       3.0    Chennai   2023-07-20
20         1039  Smartphone  36262.14       3.0  Bangalore   2021-02-15
21         1041     Desktop  36262.14       2.0    Chennai   2021-01-01
22         1008      Laptop  60000.00       4.0    Chennai   2021-04-16
23         1049  Smartphone  30000.00       2.0    Chennai   2022-02-25
24         1026      Laptop  15000.00       4.0  Bangalore   2023-03-22
25         1065      Tablet  30000.00       4.0  Bangalore   2021-01-31
26         1004      Tablet  15000.00       3.0    Chennai   2022-04-11
27         1028     Desktop  60000.00       4.0       Pune   2021-05-16
28         1036      Tablet  60000.00       1.0      Delhi   2022-05-11
29         1037      Tablet  36262.14       3.0      Delhi   2023-03-22
30         1082  Smartphone  30000.00       1.0      Delhi   2022-04-11
31         1007      Laptop  36262.14       2.0  Bangalore   2023-01-06
32         1064      Laptop  30000.00       3.0  Bangalore   2021-04-01
33         1085  Smartphone  36262.14       2.0       Pune   2021-04-16
34         1016     Desktop  45000.00       3.0      Delhi   2023-08-19
35         1070      Laptop  45000.00       2.0      Delhi   2023-04-21
36         1088      Tablet  45000.00       4.0    Chennai   2023-09-18
37         1044      Laptop  45000.00       2.0  Bangalore   2023-05-21
38         1003      Tablet  15000.00       2.0      Delhi   2023-12-02
39         1035     Desktop  45000.00       4.0       Pune   2023-03-07
40         1069  Smartphone  60000.00       3.0       Pune   2023-09-18
41         1030      Laptop  60000.00       4.0      Delhi   2023-01-21
42         1018  Smartphone  15000.00       1.0  Bangalore   2021-04-16
43         1060      Laptop  45000.00       4.0       Pune   2022-05-11
44         1053      Tablet  45000.00       1.0    Chennai   2022-05-26
45         1038  Smartphone  45000.00       4.0       Pune   2022-04-11
46         1090      Laptop  36262.14       1.0     Mumbai   2022-11-07
47         1073      Tablet  30000.00       2.0     Mumbai   2021-08-14
48         1089  Smartphone  36262.14       2.0  Bangalore   2023-10-03
49         1018  Smartphone  30000.00       3.0      Delhi   2022-06-25
50         1038      Laptop  45000.00       4.0  Bangalore   2023-03-07
51         1066      Laptop  45000.00       2.0  Bangalore   2021-07-15
52         1044      Laptop  36262.14       3.0  Bangalore   2023-03-22
53         1012      Tablet  36262.14       3.0  Bangalore   2022-12-07
54         1091      Laptop  30000.00       1.0    Chennai   2021-04-01
55         1057  Smartphone  60000.00       2.0    Chennai   2021-04-01
56         1019  Smartphone  30000.00       2.0       Pune   2022-04-26
57         1091      Laptop  36262.14       2.0     Mumbai   2021-11-27
58         1071      Laptop  36262.14       2.0  Bangalore   2021-09-28
59         1060     Desktop  15000.00       4.0       Pune   2021-09-28
60         1038  Smartphone  36262.14       2.0     Mumbai   2022-06-10
61         1000      Tablet  15000.00       2.0      Delhi   2022-02-25
62         1002     Desktop  60000.00       2.0    Chennai   2023-06-05
63         1076      Laptop  30000.00       4.0     Mumbai   2021-01-16
64         1091      Laptop  30000.00       1.0      Delhi   2021-01-01
65         1061  Smartphone  15000.00       2.0     Mumbai   2022-11-22
66         1062      Laptop  30000.00       1.0    Chennai   2023-10-18
67         1024      Tablet  36262.14       1.0    Chennai   2021-10-13
68         1055  Smartphone  45000.00       1.0       Pune   2021-05-31
69         1032      Laptop  15000.00       3.0  Bangalore   2021-01-16
70         1037  Smartphone  30000.00       3.0     Mumbai   2023-09-18
71         1005      Laptop  15000.00       1.0     Mumbai   2021-06-15
72         1057      Laptop  15000.00       2.0      Delhi   2021-10-13
73         1043      Laptop  45000.00       4.0    Chennai   2021-03-02
74         1044      Tablet  36262.14       4.0     Mumbai   2022-06-25
75         1031      Tablet  15000.00       2.0    Chennai   2022-07-10
76         1044  Smartphone  30000.00       2.0     Mumbai   2021-05-01
77         1060      Laptop  60000.00       3.0       Pune   2023-02-20
78         1046      Laptop  15000.00       1.0  Bangalore   2022-10-08
79         1020      Tablet  15000.00       2.0     Mumbai   2021-12-12
80         1079      Laptop  45000.00       4.0    Chennai   2022-03-12
81         1084      Tablet  36262.14       3.0       Pune   2023-05-21
82         1074      Laptop  60000.00       3.0     Mumbai   2021-07-15
83         1035  Smartphone  30000.00       1.0      Delhi   2021-05-01
84         1098      Laptop  60000.00       4.0  Bangalore   2022-08-09
85         1018      Laptop  30000.00       2.0     Mumbai   2023-09-03
86         1019     Desktop  36262.14       3.0       Pune   2021-12-27
87         1056      Tablet  30000.00       1.0      Delhi   2023-12-17
88         1017      Laptop  45000.00       2.0       Pune   2021-11-12
89         1046      Laptop  45000.00       4.0       Pune   2021-02-15
90         1048     Desktop  45000.00       3.0      Delhi   2022-01-11
91         1013     Desktop  45000.00       2.0       Pune   2023-05-06
92         1014      Tablet  60000.00       2.0      Delhi   2022-02-25
93         1030     Desktop  36262.14       2.0     Mumbai   2022-06-25
94         1000  Smartphone  30000.00       3.0      Delhi   2023-11-02
95         1053     Desktop  30000.00       3.0      Delhi   2021-09-13
96         1002  Smartphone  45000.00       2.0  Bangalore   2022-09-08
97         1015      Tablet  45000.00       4.0      Delhi   2022-08-24
98         1086      Tablet  15000.00       1.0      Delhi   2022-07-10
99         1056      Tablet  36262.14       2.0     Mumbai   2022-05-11
100        1074      Tablet  60000.00       2.0  Bangalore   2021-08-29
101        1011      Tablet  30000.00       1.0    Chennai   2022-06-25
102        1073  Smartphone  15000.00       2.0     Mumbai   2021-12-27
103        1095  Smartphone  15000.00       3.0     Mumbai   2022-01-26
104        1015      Tablet  30000.00       2.0    Chennai   2023-04-21
105        1071     Desktop  60000.00       1.0      Delhi   2022-03-27
106        1075      Laptop  15000.00       1.0       Pune   2021-03-17
107        1023      Tablet  15000.00       1.0  Bangalore   2022-08-09
108        1027     Desktop  36262.14       1.0       Pune   2021-06-15
109        1007      Laptop  60000.00       1.0    Chennai   2023-02-20
110        1091      Tablet  15000.00       2.0     Mumbai   2023-11-17
111        1035      Tablet  60000.00       2.0     Mumbai   2021-05-16
112        1089  Smartphone  30000.00       3.0  Bangalore   2022-10-23
113        1007      Laptop  45000.00       3.0     Mumbai   2021-08-29
114        1057      Laptop  15000.00       3.0     Mumbai   2022-01-11
115        1059     Desktop  36262.14       3.0  Bangalore   2023-07-05
116        1049  Smartphone  30000.00       2.0  Bangalore   2022-11-07
117        1027  Smartphone  60000.00       4.0    Chennai   2023-08-04
118        1091  Smartphone  30000.00       2.0     Mumbai   2021-01-16
119        1040  Smartphone  15000.00       1.0     Mumbai   2023-03-07
120        1074      Laptop  45000.00       2.0  Bangalore   2021-08-14
121        1017     Desktop  45000.00       2.0       Pune   2022-08-09
122        1075     Desktop  30000.00       1.0       Pune   2021-09-28
123        1008      Laptop  60000.00       1.0    Chennai   2021-09-13
124        1073      Laptop  15000.00       2.0      Delhi   2021-01-01

In [53]:
ds['Quantity']=ds['Quantity'].astype(int)

In [56]:
print(ds.to_string())

     CustomerID     Product     Price  Quantity       City PurchaseDate
0          1052     Desktop  36262.14         4  Bangalore   2021-06-30
1          1041     Desktop  36262.14         3      Delhi   2023-01-21
2          1057  Smartphone  45000.00         2  Bangalore   2023-04-06
3          1038      Tablet  45000.00         1    Chennai   2023-07-05
4          1013  Smartphone  45000.00         2     Mumbai   2022-04-11
5          1094      Laptop  60000.00         2     Mumbai   2022-03-12
6          1004      Laptop  30000.00         2    Chennai   2022-02-25
7          1034      Laptop  30000.00         2    Chennai   2022-12-22
8          1086      Laptop  30000.00         3      Delhi   2022-10-23
9          1092     Desktop  30000.00         3     Mumbai   2022-03-12
10         1074      Laptop  45000.00         2  Bangalore   2021-08-14
11         1017     Desktop  45000.00         2       Pune   2022-08-09
12         1075     Desktop  30000.00         1       Pune   2021-09-28
13         1008      Laptop  60000.00         1    Chennai   2021-09-13
14         1073      Laptop  15000.00         2      Delhi   2021-01-01
15         1057      Tablet  15000.00         2       Pune   2022-11-22
16         1016  Smartphone  60000.00         4     Mumbai   2023-09-03
17         1006      Laptop  30000.00         3    Chennai   2022-07-10
18         1045      Tablet  45000.00         1  Bangalore   2023-01-21
19         1012      Tablet  15000.00         3    Chennai   2023-07-20
20         1039  Smartphone  36262.14         3  Bangalore   2021-02-15
21         1041     Desktop  36262.14         2    Chennai   2021-01-01
22         1008      Laptop  60000.00         4    Chennai   2021-04-16
23         1049  Smartphone  30000.00         2    Chennai   2022-02-25
24         1026      Laptop  15000.00         4  Bangalore   2023-03-22
25         1065      Tablet  30000.00         4  Bangalore   2021-01-31
26         1004      Tablet  15000.00         3    Chennai   2022-04-11
27         1028     Desktop  60000.00         4       Pune   2021-05-16
28         1036      Tablet  60000.00         1      Delhi   2022-05-11
29         1037      Tablet  36262.14         3      Delhi   2023-03-22
30         1082  Smartphone  30000.00         1      Delhi   2022-04-11
31         1007      Laptop  36262.14         2  Bangalore   2023-01-06
32         1064      Laptop  30000.00         3  Bangalore   2021-04-01
33         1085  Smartphone  36262.14         2       Pune   2021-04-16
34         1016     Desktop  45000.00         3      Delhi   2023-08-19
35         1070      Laptop  45000.00         2      Delhi   2023-04-21
36         1088      Tablet  45000.00         4    Chennai   2023-09-18
37         1044      Laptop  45000.00         2  Bangalore   2023-05-21
38         1003      Tablet  15000.00         2      Delhi   2023-12-02
39         1035     Desktop  45000.00         4       Pune   2023-03-07
40         1069  Smartphone  60000.00         3       Pune   2023-09-18
41         1030      Laptop  60000.00         4      Delhi   2023-01-21
42         1018  Smartphone  15000.00         1  Bangalore   2021-04-16
43         1060      Laptop  45000.00         4       Pune   2022-05-11
44         1053      Tablet  45000.00         1    Chennai   2022-05-26
45         1038  Smartphone  45000.00         4       Pune   2022-04-11
46         1090      Laptop  36262.14         1     Mumbai   2022-11-07
47         1073      Tablet  30000.00         2     Mumbai   2021-08-14
48         1089  Smartphone  36262.14         2  Bangalore   2023-10-03
49         1018  Smartphone  30000.00         3      Delhi   2022-06-25
50         1038      Laptop  45000.00         4  Bangalore   2023-03-07
51         1066      Laptop  45000.00         2  Bangalore   2021-07-15
52         1044      Laptop  36262.14         3  Bangalore   2023-03-22
53         1012      Tablet  36262.14         3  Bangalore   2022-12-07
54         1091      Laptop  30000.00         1    Chennai   2021-04-01
55         1057  Smartphone  60000.00         2    Chennai   2021-04-01
56         1019  Smartphone  30000.00         2       Pune   2022-04-26
57         1091      Laptop  36262.14         2     Mumbai   2021-11-27
58         1071      Laptop  36262.14         2  Bangalore   2021-09-28
59         1060     Desktop  15000.00         4       Pune   2021-09-28
60         1038  Smartphone  36262.14         2     Mumbai   2022-06-10
61         1000      Tablet  15000.00         2      Delhi   2022-02-25
62         1002     Desktop  60000.00         2    Chennai   2023-06-05
63         1076      Laptop  30000.00         4     Mumbai   2021-01-16
64         1091      Laptop  30000.00         1      Delhi   2021-01-01
65         1061  Smartphone  15000.00         2     Mumbai   2022-11-22
66         1062      Laptop  30000.00         1    Chennai   2023-10-18
67         1024      Tablet  36262.14         1    Chennai   2021-10-13
68         1055  Smartphone  45000.00         1       Pune   2021-05-31
69         1032      Laptop  15000.00         3  Bangalore   2021-01-16
70         1037  Smartphone  30000.00         3     Mumbai   2023-09-18
71         1005      Laptop  15000.00         1     Mumbai   2021-06-15
72         1057      Laptop  15000.00         2      Delhi   2021-10-13
73         1043      Laptop  45000.00         4    Chennai   2021-03-02
74         1044      Tablet  36262.14         4     Mumbai   2022-06-25
75         1031      Tablet  15000.00         2    Chennai   2022-07-10
76         1044  Smartphone  30000.00         2     Mumbai   2021-05-01
77         1060      Laptop  60000.00         3       Pune   2023-02-20
78         1046      Laptop  15000.00         1  Bangalore   2022-10-08
79         1020      Tablet  15000.00         2     Mumbai   2021-12-12
80         1079      Laptop  45000.00         4    Chennai   2022-03-12
81         1084      Tablet  36262.14         3       Pune   2023-05-21
82         1074      Laptop  60000.00         3     Mumbai   2021-07-15
83         1035  Smartphone  30000.00         1      Delhi   2021-05-01
84         1098      Laptop  60000.00         4  Bangalore   2022-08-09
85         1018      Laptop  30000.00         2     Mumbai   2023-09-03
86         1019     Desktop  36262.14         3       Pune   2021-12-27
87         1056      Tablet  30000.00         1      Delhi   2023-12-17
88         1017      Laptop  45000.00         2       Pune   2021-11-12
89         1046      Laptop  45000.00         4       Pune   2021-02-15
90         1048     Desktop  45000.00         3      Delhi   2022-01-11
91         1013     Desktop  45000.00         2       Pune   2023-05-06
92         1014      Tablet  60000.00         2      Delhi   2022-02-25
93         1030     Desktop  36262.14         2     Mumbai   2022-06-25
94         1000  Smartphone  30000.00         3      Delhi   2023-11-02
95         1053     Desktop  30000.00         3      Delhi   2021-09-13
96         1002  Smartphone  45000.00         2  Bangalore   2022-09-08
97         1015      Tablet  45000.00         4      Delhi   2022-08-24
98         1086      Tablet  15000.00         1      Delhi   2022-07-10
99         1056      Tablet  36262.14         2     Mumbai   2022-05-11
100        1074      Tablet  60000.00         2  Bangalore   2021-08-29
101        1011      Tablet  30000.00         1    Chennai   2022-06-25
102        1073  Smartphone  15000.00         2     Mumbai   2021-12-27
103        1095  Smartphone  15000.00         3     Mumbai   2022-01-26
104        1015      Tablet  30000.00         2    Chennai   2023-04-21
105        1071     Desktop  60000.00         1      Delhi   2022-03-27
106        1075      Laptop  15000.00         1       Pune   2021-03-17
107        1023      Tablet  15000.00         1  Bangalore   2022-08-09
108        1027     Desktop  36262.14         1       Pune   2021-06-15
109        1007      Laptop  60000.00         1    Chennai   2023-02-20
110        1091      Tablet  15000.00         2     Mumbai   2023-11-17
111        1035      Tablet  60000.00         2     Mumbai   2021-05-16
112        1089  Smartphone  30000.00         3  Bangalore   2022-10-23
113        1007      Laptop  45000.00         3     Mumbai   2021-08-29
114        1057      Laptop  15000.00         3     Mumbai   2022-01-11
115        1059     Desktop  36262.14         3  Bangalore   2023-07-05
116        1049  Smartphone  30000.00         2  Bangalore   2022-11-07
117        1027  Smartphone  60000.00         4    Chennai   2023-08-04
118        1091  Smartphone  30000.00         2     Mumbai   2021-01-16
119        1040  Smartphone  15000.00         1     Mumbai   2023-03-07
120        1074      Laptop  45000.00         2  Bangalore   2021-08-14
121        1017     Desktop  45000.00         2       Pune   2022-08-09
122        1075     Desktop  30000.00         1       Pune   2021-09-28
123        1008      Laptop  60000.00         1    Chennai   2021-09-13
124        1073      Laptop  15000.00         2      Delhi   2021-01-01

In [59]:
ds.to_csv("Cleaned_data_pr2.csv",index=False)